name: Build Godot Project
permissions:
  contents: write

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [web, linux, windows, mac]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          preset: ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

      - name: Write changes to repository
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
