name: Build Godot Project
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [HTML5, linux, windows, mac]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          preset: ${{ matrix.platform }}

      - name: Write changes to repository
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
    
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
